-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
-- // set a keymap for pressing space t to activate :ToggleTerm
-- vim.api.nvim_set_keymap("n", "<Space>t", ":ToggleTerm<CR>", { silent = true })
--vim.api.nvim_set_keymap("n", "<Space>t", ":ToggleTerm<CR>", { silent = true })
-- // set a keymap for option t to toggle terminals
